# Generated by Django 3.2.4 on 2021-06-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PitchParser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField(default=0)),
                ('value', models.CharField(max_length=200)),
                ('category', models.TextField()),
            ],
        ),
    ]
