# Generated by Django 3.2.4 on 2021-06-10 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitchparser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PitchParser',
        ),
    ]
