# Generated by Django 3.2.4 on 2021-06-10 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_alter_fileupload_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='title',
        ),
    ]
